### ISSUE TITLE
KnowledgeDistillation Layer cannot backpropagate to soft label nor label inputs.

### ISSUE THREAD

**Issue by pasxalinamed** [wentianli/knowledge_distillation_caffe#2]
I am trying to test knowledge distilation with cifar_10 example of caffe. However it shows the error "KnowledgeDistillation Layer cannot backpropagate to soft label nor label inputs."

My training prototxt is this

[distillation_cifar10_quick_train_test.txt](https://github.com/wentianli/knowledge_distillation_caffe/files/1521921/distillation_cifar10_quick_train_test.txt)

**Comment by wentianli** [comment]
Usually the teacher network is fixed(not receiving any gradient). Therefore, in my implementation, KnowledgeDistillation Layer only backpropagates to its **first bottom**, which should be "student_ip2" in your prototxt. Plus, you didn't freeze the teacher network properly, please refer to README.

**Comment by pasxalinamed** [comment]
Thank you for your answer. Changing student_ip2 as the first bottom solver this issue.
