### ISSUE TITLE
Using two KnowledgeDistillation layers at the same prototxt

### ISSUE THREAD

**Issue by pasxalinamed** [wentianli/knowledge_distillation_caffe#3]
Can we use two KnowledgeDistillation layers at the same prototxt?
I want to implement knowledge distillation on PVANet (https://github.com/sanghoon/pva-faster-rcnn)
which has two losses. One for region proposal and one for bbox classification. Is it wrong if I use only one KnowledgeDistillation layer, for example only for bbox classification?

**Comment by wentianli** [comment]
Distillation in faster-rcnn barely worked for me (mAP only improved a tiny bit), but [this one](http://openaccess.thecvf.com/content_cvpr_2017/papers/Li_Mimicking_Very_Efficient_CVPR_2017_paper.pdf) does. You may have a try.
Anyway, to your question, two distillation layers or one is up to your choice, as long as no error occurs. However, if the teacher and student network each has a RPN layer, they will generate **different ROIs** which makes distilling the bboxes irrelevant. Therefore, to distill bbox classification, you should only keep one RPN layer to generate ROIs for both networks.

**Comment by pasxalinamed** [comment]
@wentianli  Can you give an example? How did you used knowledge distillation layer to implement 'Mimicking Very Efficient Network for Object Detection'?
Thank you

**Comment by wentianli** [comment]
@pasxalinamed 'Mimicking ...' is a different method. You can write a python layer to implement it. I can't release the code that I used (someone else wrote it).

**Comment by yonger001** [comment]
> Can we use two KnowledgeDistillation layers at the same prototxt?
> I want to implement knowledge distillation on PVANet (https://github.com/sanghoon/pva-faster-rcnn)
> which has two losses. One for region proposal and one for bbox classification. Is it wrong if I use only one KnowledgeDistillation layer, for example only for bbox classification?

hi, I met the same question was U, for different loss Func, do we need to use the different KL-distillation-layers? looking for Ur reply,thank you very much!

**Comment by yonger001** [comment]
@pasxalinamed  hi, I met the same question was U, for different loss Func, do we need to use the different KL-distillation-layers? looking for Ur reply,thank you very much!
