### ISSUE TITLE
The data and label should have the same first dimension. 

### ISSUE THREAD

**Issue by pasxalinamed** [wentianli/knowledge_distillation_caffe#4]
Hi, I encounter the following problem after iteration 150 of the training:
I1208 08:51:16.048475 7276 layer_factory.hpp:77] Creating layer rpn_loss_cls
F1208 08:51:16.049386 7276 loss_layer.cpp:19] Check failed: bottom[0]->shape(0) == bottom[1]->shape(0) (128 vs. 119) The data and label should have the same first dimension.
*** Check failure stack trace: ***
Before this iteration the training was running fine
Note that 128 is the batch size I use for training. Should I use batch size=1?

**Comment by wentianli** [comment]
As far as I know, certain Faster R-CNN implementations do not support a batch size other than 1. It might be the reason you got this error.
